const data = {
    products:[
        {
            _id:'1',
            name: 'Apple',
            category: 'laptop',
            image:'/images/product-1.jpg',
            price:120,
            brand:'Apple',
            rating: 4.5,
            numReviews:10,
            description: 'high quality apple laptop',
        },
        {
            _id:'2',
            name: 'HP255',
            category: 'laptop',
            image:'/images/product-2.jpg',
            price:1000,
            brand:'Apple',
            rating: 4.5,
            numReviews:10,
            description: 'high quality apple laptop',
        },
        {
            _id:'3',
            name: 'Apple 300',
            category: 'laptop',
            image:'/images/product-3.jpg',
            price:300,
            brand:'Apple',
            rating: 4.5,
            numReviews:10,
            description: 'high quality apple laptop',
        },
        {
            _id:'4',
            name: 'Apple',
            category: 'laptop',
            image:'/images/product-4.jpg',
            price:60,
            brand:'Apple',
            rating: 4.5,
            numReviews:10,
            description: 'high quality apple laptop',
        },
        {
            _id:'5',
            name: 'Apple',
            category: 'laptop',
            image:'/images/product-1.jpg',
            price:250,
            brand:'Apple',
            rating: 4.5,
            numReviews:10,
            description: 'high quality apple laptop',
        },
        {
            _id:'6',
            name: 'Apple',
            category: 'laptop',
            image:'/images/product-2.jpg',
            price:200,
            brand:'Apple',
            rating: 4.5,
            numReviews:10,
            description: 'high quality apple laptop',
        },

    ],
};

export default data;